name: newbox-bot

services:
  redis:
    image: redis/redis-stack-server:7.2.0-v10
    container_name: newbox-bot-redis
    volumes:
      - .docker/redis/redis.conf/:/redis-stack.conf
      - .docker/redis/data/:/data
      - .docker/redis/log:/var/log/redis
    ports:
      - 6384:6379
    restart: unless-stopped
    networks:
      - newbox-bot

networks:
  newbox-bot:
    driver: bridge
